In [1]:
import numpy as np

In [5]:
list1=[1,2,3,4,5] #Creating a list

In [6]:
type(list1)

list

In [7]:
arr=np.array(list1) # converting list into one dimensional array using np

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr.shape  #results shows its just one dimensional array

(5,)

### Creating Multi dimensional array

In [32]:
list1=[1,2,3,4,5]
list2=[3,4,5,6,8]
list3=[5,6,4,8,9]

In [33]:
arr=np.array([list1,list2,list3])

In [49]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 8],
       [5, 6, 4, 8, 9]])

In [35]:
arr.shape # result shows its 2 dimensional array

(3, 5)

In [36]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [8, 5, 6],
       [4, 8, 9]])

In [37]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 3, 4, 5, 6, 8, 5, 6, 4, 8, 9]])

### Indexing Array

In [38]:
# Creating a new array and finding an element using indexing

arr1=np.array([1,2,3,4,5,6,7,8,9])

In [39]:
arr1[3]

4

In [52]:
#indexing multi dimensional array
#Recreating the earlier array

list4=[1,2,3,4,5]
list5=[3,4,5,6,8]
list6=[5,6,4,8,9]

In [54]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 8],
       [5, 6, 4, 8, 9]])

In [55]:
arr[1:,2:]

array([[5, 6, 8],
       [4, 8, 9]])

In [56]:
arr[:,2:]

array([[3, 4, 5],
       [5, 6, 8],
       [4, 8, 9]])

### Some Array Functions

In [69]:
arr=np.arange(0,10)

In [64]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr=np.arange(0,10,step=2)

In [66]:
arr

array([0, 2, 4, 6, 8])

In [67]:
arr=np.linspace(1,10,50)

In [68]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Copy Function and BroadCating

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[3:]=500

In [73]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [74]:
#replacing or copying above 'arr' array in new array
arr1=arr

In [75]:
arr1[3:]=1000

In [76]:
arr1

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [77]:
arr  # the result shows both 'arr'and 'arr1'are same

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [78]:
# using copy function to avoid this situation

arr1=arr.copy()

In [79]:
arr

array([   0,    1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [80]:
arr1[3:]=2000

In [81]:
print(arr1)
print(arr)

[   0    1    2 2000 2000 2000 2000 2000 2000 2000]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


### Some Functions Usefull for exploratory analysis

In [82]:
arr<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [87]:
arr[arr<3] # Displayes elements,not just true and false

array([0, 1, 2])

In [84]:
arr*5

array([   0,    5,   10, 5000, 5000, 5000, 5000, 5000, 5000, 5000])

In [85]:
arr/2

array([  0. ,   0.5,   1. , 500. , 500. , 500. , 500. , 500. , 500. ,
       500. ])

In [88]:
np.ones(5)
    

array([1., 1., 1., 1., 1.])

In [89]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [91]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
np.random.rand(3,3) #selects random distribution of values between 0 to 1

array([[0.25976976, 0.22123698, 0.23493528],
       [0.55713468, 0.33745263, 0.11377113],
       [0.81716457, 0.85621097, 0.94148491]])

In [94]:
np.random.randn(3,3) # selects random distribution of from standard normal distribution

array([[ 1.23169789, -0.71170528,  0.13905942],
       [ 0.98318034, -1.24730097, -3.5943138 ],
       [-0.49158644, -0.16962259, -0.59283563]])

In [95]:
np.random.randint(0,50,10) #selects 10 random integer value between 0 to 50

array([24,  1, 31, 34, 10,  5, 44, 31,  0, 17])